### ISSUE TITLE
Ballerina needs a logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/website-icons#10]
The Ballerina track needs a logo.

The official logo is on https://ballerina.io/ and the short version is just the ballet shoes (seen on twitter at https://twitter.com/ballerinalang)

The maintainers of the Ballerina track are also the developers of the language (in case you have questions).

**Comment by kytrinyx** [comment]
@iHiD @nicolechalmers It looks like @github/ballerina is getting ready to launch. Is there any chance of getting their icon done soon-ish?

**Comment by iHiD** [comment]
Yes :) (cc @nicolechalmers)
