### ISSUE TITLE
Add icon for wasm track

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/website-icons#105]
See https://github.com/exercism/wasm

**Comment by iHiD** [comment]
@ErikSchierboom  - any thoughts on what the icon should be?

**Comment by taiyab** [comment]
@ErikSchierboom @iHiD https://github.com/exercism/website-icons/pull/107

**Comment by iHiD** [comment]
Great! :)

**Comment by ErikSchierboom** [comment]
Closed by #107
