### ISSUE TITLE
Icon for Elixir learning exercise "dancing dots"

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/website-icons#112]
Exercise: https://exercism.org/tracks/elixir/exercises/dancing-dots

The story is about making generative art that's just dots. Anything that's a few different scattered circles would work as an icon.

**Comment by taiyab** [comment]
@ErikSchierboom Don't have my local setup yet (installing now), could you PR this for me?

![dancing-dots](https://user-images.githubusercontent.com/5337876/186673893-f55c7e3f-e52b-4696-8dd0-6d76df8cf312.svg)

**Comment by ErikSchierboom** [comment]
@taiyab Yep, sure

**Comment by ErikSchierboom** [comment]
PR submitted: 127
