### ISSUE TITLE
REST-api exercise has no icon

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/website-icons#12]
![46675039-e2ea0a80-cbdd-11e8-93a9-a3543f85300b](https://user-images.githubusercontent.com/135246/46680264-fc448400-cbe8-11e8-8543-e954b77de8f4.png)

**Comment by rpottsoh** [comment]
[description.md](https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/description.md), in case the artist needs some inspiration.... :smile:
