### ISSUE TITLE
Icon for new ABAP Exercise: ITAB Aggregation

### ISSUE THREAD

**Issue by marianfoo** [exercism/website-icons#125]
Link https://exercism.org/tracks/abap/exercises/itab-aggregation

This exercise is one of four new exercises created by SAP to demonstrate the use of internal tables and their functions.
- https://github.com/exercism/website-icons/issues/123
- https://github.com/exercism/website-icons/issues/124
- https://github.com/exercism/website-icons/issues/125
- https://github.com/exercism/website-icons/issues/126

SAP will make a special month for ABAP in September and promote different things around it. Among them also these exercises.
It would be great if by then these exercises would have icons.

Thanks!

**Comment by larshp** [comment]
this is done, can be closed

**Comment by marianfoo** [comment]
Thank you for the icons!
