### ISSUE TITLE
Icon for new ABAP Exercise: ITAB Nesting

### ISSUE THREAD

**Issue by marianfoo** [exercism/website-icons#126]
Link https://exercism.org/tracks/abap/exercises/itab-nesting

This exercise is one of four new exercises created by SAP to demonstrate the use of internal tables and their functions.
- https://github.com/exercism/website-icons/issues/123
- https://github.com/exercism/website-icons/issues/124
- https://github.com/exercism/website-icons/issues/125
- https://github.com/exercism/website-icons/issues/126

SAP will make a special month for ABAP in September and promote different things around it. Among them also these exercises.
It would be great if by then these exercises would have icons.

Thanks!

**Comment by taiyab** [comment]
@ErikSchierboom Could you PR these for me? Local setup is still bugging me out.

Thanks.


![itab-nesting](https://user-images.githubusercontent.com/5337876/188924857-840d9e90-00f8-49c1-b897-8838c0656839.svg)
![itab-combination](https://user-images.githubusercontent.com/5337876/188924853-fca15e1c-2d80-460f-b0c1-0f4fd1f6c659.svg)

![itab-basics](https://user-images.githubusercontent.com/5337876/188924847-f69baa76-0f9d-450b-9c71-5dae80a7916d.svg)
![itab-aggregation](https://user-images.githubusercontent.com/5337876/188924841-b582cabd-9cd4-48d6-b820-f6e5f6345627.svg)

**Comment by iHiD** [comment]
Great. Thanks @taiyab. Erik's off so I've done it #128.

**Comment by iHiD** [comment]
All done - they look fantastic. Thanks!

https://exercism.org/tracks/abap/exercises?criteria=itab
