### ISSUE TITLE
Track icon for Chapel

### ISSUE THREAD

**Issue by lucaferranti** [exercism/website-icons#131]
The [Chapel track](https://github.com/exercism/chapel) is proceeding fast forwards and approaching launch. Would be great to get a icon for it.

Chapel has an official logo, which can be found [here](https://chapel-lang.org/logo.html) (the first). Necessary attributions of the logo are described on the same page and also [here](https://github.com/chapel-lang/chapel/blob/main/CONTRIBUTORS.md#logo-design).

**Comment by ErikSchierboom** [comment]
@iHiD Could you create the logo?

**Comment by iHiD** [comment]
@lucaferranti Do you have an SVG of the official logo?

**Comment by lucaferranti** [comment]
@iHiD could not find one, but I've asked in the Chapel gitter to double check

**Comment by iHiD** [comment]
Thanks. I converted it.
