### ISSUE TITLE
Track icon for V

### ISSUE THREAD

**Issue by 1ethanhansen** [exercism/website-icons#139]
Requesting a track icon for the [V track](https://github.com/exercism/vlang)

- Does the language have an official logo? **yes**
  - https://github.com/vlang/v-logo
  - licensed under the [MIT license](https://github.com/vlang/v-logo/blob/master/LICENSE)

**Comment by iHiD** [comment]
@taiyab Would you mind obliging please? Thanks!

**Comment by glennj** [comment]
Added in #144
