### ISSUE TITLE
Track icon for 8th

### ISSUE THREAD

**Issue by axtens** [exercism/website-icons#142]
Requesting a track icon for the [8th track](https://github.com/exercism/8th)

    Does the language have an official logo? yes
        https://8th-dev.com/images/8thheader1.png
        This is a proprietary logo. Do I need written permission?

**Comment by axtens** [comment]
Just in case, I've written to the owner requesting permission.

**Comment by ErikSchierboom** [comment]
You likely do need permission.

**Comment by axtens** [comment]
> To Whom it may concern:
>
> Aaron High-Tech, Ltd. grants permission to Bruce Axtens to use the icon associated with 8th (in the files man/logo.svg and/or man/logo.png) in the 8th distribution, as an icon to identify the 8th learning track on Excercism.
>
> Ron Aaron
> CTO/Owner Aaron High-Tech, Ltd
> +972 52.652.5543

**Comment by ErikSchierboom** [comment]
@taiyab Could you create an icon for the 8th track? Details are in this thread.

**Comment by glennj** [comment]
Added in #144
