### ISSUE TITLE
Cloudfront needs to expire when something is added to this repo

### ISSUE THREAD

**Issue by iHiD** [exercism/website-icons#147]
See https://github.com/exercism/website-icons/pull/141 for context.

As part of the GHA we need to invalidate any paths in cloudfront that have changed. So for example, to solve the issue above I created an Cloudfront invalidation for `/tracks/pharo-smalltalk.svg`

**Comment by ErikSchierboom** [comment]
Note to self: we'll need to get the commit programmatically to get the changes files as the `push` event doesn't prepopulate that data: https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit

**Comment by ErikSchierboom** [comment]
This was done in https://github.com/exercism/website-icons/pull/150
