### ISSUE TITLE
Icon for C++ concept exercise "last will"

### ISSUE THREAD

**Issue by vaeng** [exercism/website-icons#155]
Exercise PR: https://github.com/exercism/cpp/pull/610

The story is about executing a testament. It involves four different families, each has to give a secret code. The combined code will open a mysterious vault. It also features a red and a blue code part.

So anything with some kind of vault, and/or red and blue codes/keys would work as an icon.

**Comment by vaeng** [comment]
The exercise is now done: https://exercism.org/tracks/cpp/exercises/last-will, only misses an icon.

**Comment by iHiD** [comment]
@taiyab Any chance you could do this pls?

**Comment by vaeng** [comment]
Would it be better if I make a temporary icon until someone more designer-ish takes up the task? @iHiD

**Comment by iHiD** [comment]
No, but thank you. I'd rather they have the default ones. It's on my radar to bash through a wad of these though.
