### ISSUE TITLE
Add icon for GDScript track

### ISSUE THREAD

**Issue by pfertyk** [exercism/website-icons#169]
All initial exercises are implemented and the [GDScript track](https://exercism.org/tracks/gdscript) will be ready soon ;) We're adding the docs etc. in preparation for the launch. We also need a track icon.

GDScript does not have an official logo. This language is part of Godot Engine, with Godot Editor being the default IDE.

Together with @ErikSchierboom and @BNAndras we decided to use this icon (an official logo of Godot Engine):

https://godotengine.org/assets/press/icon_color.svg

The license for all Godot Engine's icons is [Creative Commons Attribution 4.0 International](https://github.com/godotengine/godot/blob/master/LOGO_LICENSE.txt).

The official [Press Kit](https://godotengine.org/press/) can be helpful here as well.

**Comment by ErikSchierboom** [comment]
@iHiD Something for you
