### ISSUE TITLE
Please create icon for Euphoria language track

### ISSUE THREAD

**Issue by axtens** [exercism/website-icons#171]
The Euphoria language has an official logo at http://rapideuphoria.com/euphoria.gif

The Unofficial logo is https://openeuphoria.org/logos/80x84-mongoose-color-lite.png and its licensing details are at https://openeuphoria.org/wiki/view/LogoLicence.wc

I have been given permission to use the unofficial (Open)Euphoria logo for the Euphoria track. My initial request can be seen at https://openeuphoria.org/forum/m/137615.wc along with a statement of permission. The permission was seconded at https://openeuphoria.org/forum/m/137616.wc

For any further details please contact @ghaberek via https://github.com/ghaberek

**Comment by iHiD** [comment]
https://github.com/exercism/website-icons/pull/172
