### ISSUE TITLE
Add logo(s) for Cairo track

### ISSUE THREAD

**Issue by misicnenad** [exercism/website-icons#176]
The complete Cairo logo kit (link below) includes PNG and SVG variations of the following:
- horizontal text logo
- vertical text logo
- just logo

Link to the kit:
https://www.starknet.io/media-kit/#cairo-logo-kit

Cairo track repo: https://github.com/exercism/cairo

**Comment by iHiD** [comment]
I've sent the SVG to Erik to deploy :)

**Comment by misicnenad** [comment]
A related PR https://github.com/exercism/website-icons/pull/177 has been merged, should we close the issue?

**Comment by misicnenad** [comment]
@iHiD just pinging you about closing this issue, see https://github.com/exercism/website-icons/issues/176#issuecomment-2232613546

**Comment by misicnenad** [comment]
@ErikSchierboom is there anything else to do for this issue?

**Comment by ErikSchierboom** [comment]
Nope. This can be closed
