### ISSUE TITLE
Lisp Flavoured Erlang icon

### ISSUE THREAD

**Issue by kytrinyx** [exercism/website-icons#2]
One thing that I noticed is that the LFE icon doesn't have the characteristic "lambda" floating on the coffee.

The key thing about LFE is that it's a combination of Erlang https://v2.exercism.io/tracks/erlang and Lisp

I wonder if the coffee thing has too much detail. Maybe we could do a combination of the lambda and the erlang E instead?

**Comment by iHiD** [comment]
This has been done.
