### ISSUE TITLE
ceylon.png should be changed to the Ceylon logo (not Nim's) and then regenerating its track-images

### ISSUE THREAD

**Issue by petertseng** [exercism/website-icons#20]
As we can see at https://ceylon-lang.org/blog/2013/12/13/three-legged-elephants/, Ceylon's mascot (and thus its logo) is an elephant.

Thus, I suggest that https://github.com/exercism/website-icons/blob/master/tracks/logos/ceylon.png be changed to be such an elephant, matching https://github.com/exercism/website-icons/blob/master/tracks/logos/ceylon-t.png is. It would be very unfortunate if the track got mixed up with Nim (a track whose logo is a crown as seen in https://github.com/nim-lang/assets/blob/master/Art/logo-crown.png )

You may think this is unimportant since Ceylon is an unlaunched track, and you would be correct. On the other hand, it's also true that someone who somehow knows of the existence of the URL https://exercism.io/tracks/ceylon is currently able to navigate to it and confusingly see a logo that does not match Ceylon's.

So let's consider this on the list of things to be done at some point before the Ceylon track is launched, perhaps. (When will that happen? I don't know! Prioritise accordingly)

**Comment by nicolechalmers** [comment]
@petertseng Thanks for flagging this up. I agree, we need to change the [Ceylon](https://exercism.io/tracks/ceylon) logo to differentiate it from the [Nim](https://exercism.io/tracks/nim) one. I'm concerned though that an elephant Ceylon icon is too close the [PHP Track icon](https://exercism.io/tracks/php). I could perhaps change the PHP one. @kytrinyx @iHiD @petertseng I'd appreciate your thoughts on what would be most clear to folks?

I could create a new PHP track icon like this:
<img width="527" alt="Screen Shot 2019-08-09 at 14 08 15" src="https://user-images.githubusercontent.com/5421823/62781165-41f30700-baaf-11e9-8010-457861e4d3bc.png">

**Comment by nicolechalmers** [comment]
@iHiD Please replace the icon [here](https://github.com/exercism/website-icons/blob/master/tracks/logos/ceylon.png) with the one below.

ceylon-white:
![ceylon-w](https://user-images.githubusercontent.com/5421823/62783075-82548400-bab3-11e9-9946-aa5c08b78b77.png)

**Comment by iHiD** [comment]
This should now be done. It may take 24hrs for Cloudfront caches to expire.
