### ISSUE TITLE
Different logos for JavaScript track throughout site

### ISSUE THREAD

**Issue by missmatsuko** [exercism/website-icons#21]
I thought the track icons were determined within the track repos, but I guess this is the correct repo for it.

I noticed the logo/icon for the JavaScript track is different throughout the site.
https://exercism.io/tracks uses "JS" logo
https://exercism.io/my/tracks uses "ES" logo (need to be logged in to see)
https://exercism.io/tracks/javascript uses "JS" logo
https://exercism.io/#explore-languages uses "JS" logo on mobile, "ES" logo on desktop

Also don't know why there's an icon within the tracks.
They're all different from this one which is in the track repo:
https://github.com/exercism/javascript/blob/master/img/icon.png

**Comment by iHiD** [comment]
Could you clear your cache on desktop and validate that the ES one still appears in places like https://exercism.io/#explore-languages pls?

**Comment by iHiD** [comment]
> Also don't know why there's an icon within the tracks.

That can be deleted. @kytrinyx is this something we could script across tracks?

**Comment by missmatsuko** [comment]
@iHiD Still see the ES6 one on https://exercism.io/#explore-languages desktop

**Comment by nicolechalmers** [comment]
@iHiD @missmatsuko Same for me on https://exercism.io/#explore-languages desktop

I see this:

<img width="381" alt="Screen Shot 2019-08-09 at 14 42 07" src="https://user-images.githubusercontent.com/5421823/62783343-1b839a80-bab4-11e9-874a-8ee14c85bca8.png">
<img width="351" alt="Screen Shot 2019-08-09 at 14 42 09" src="https://user-images.githubusercontent.com/5421823/62783344-1b839a80-bab4-11e9-8711-b00a74c09783.png">

**Comment by iHiD** [comment]
I believe this is now fixed. Sorry it's taken me forever to get to. 

@missmatsuko Could you please let me know if they see any old ones, or otherwise close the issue if you're satisfied it's fixed. Thanks.

**Comment by missmatsuko** [comment]
Only see the "JS" version of the logo now. Thanks!
