### ISSUE TITLE
Glyph for new exercise: satellite

### ISSUE THREAD

**Issue by fidelcoria** [exercism/website-icons#22]
Howdy folks,

There is an open PR [#1424](https://github.com/exercism/problem-specifications/pull/1424) in `problem-specifications` for a new exercise named retree. Please create a new glyph for it.

~ Thank you kindly

**Comment by iHiD** [comment]
@nicolechalmers Could you take a look at this please.

**Comment by nicolechalmers** [comment]
Hey @fidelcoria,

Would either of these work (ignore colours and styling for now)?

<img width="361" alt="screen shot 2019-02-01 at 12 12 24" src="https://user-images.githubusercontent.com/5421823/52147191-c81f2400-261a-11e9-8bc3-f8d68c45bf06.png">
<img width="303" alt="screen shot 2019-02-01 at 12 12 27" src="https://user-images.githubusercontent.com/5421823/52147192-c8b7ba80-261a-11e9-9ca1-f85b9cf6844e.png">

If so, which would you prefer?

**Comment by iHiD** [comment]
@fidelcoria Also see my comment about renaming the exercise to Satellite (I think we should have this sort of satallite icon whether we rename it or not)

**Comment by fidelcoria** [comment]
Yeah, the first one makes sense for the exercise "story." 
How about a solid dish? (I know it's just styling)

**Comment by sshine** [comment]
Before merging this icon, could it be named "sattelite" instead of "retree"?

Decision made in #1451 and rename requested in #1478.

**Comment by nicolechalmers** [comment]
Sorry for the delay!

Here's a design that's a mixture of the two:

Grey:
![satellite-dark](https://user-images.githubusercontent.com/5421823/55339513-bdf29800-549a-11e9-8282-0de62dfc26ba.png)
Turquoise:
![satellite-turquoise](https://user-images.githubusercontent.com/5421823/55339514-bdf29800-549a-11e9-8d2c-73bc8a0b6c78.png)
White:
![satellite-white](https://user-images.githubusercontent.com/5421823/55339515-bdf29800-549a-11e9-82fa-b52d8343c52a.png)

**Comment by iHiD** [comment]
Merging. Thanks @nicolechalmers
