### ISSUE TITLE
Glyph for new exercise: dnd-character

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/website-icons#23]
The `dnd-character` exercise could use some glyphs :)

**Comment by iHiD** [comment]
@nicolechalmers Could you sort this pls? :)

**Comment by nicolechalmers** [comment]
I'll see what I can do!
@iHiD Where do I find an overview of what the Exercise is about so I can choose something relevant? It's been a while since I've needed to navigate to those files.

**Comment by iHiD** [comment]
Problem specifications is your best bet. The path to the description file for this is: https://github.com/exercism/problem-specifications/blob/master/exercises/dnd-character/description.md

**Comment by iHiD** [comment]
A multi-sided dice is probably best. Maybe something like [this](https://thenounproject.com/search/?q=dungeons-and-dragons&i=20125)

**Comment by ErikSchierboom** [comment]
@nicolechalmers I know you are very busy, but I was wondering what your thoughts are on my comment above.

**Comment by iHiD** [comment]
I know @nicolechalmers was doing that (I sneaked a peak over her shoulder) but I don't think it got finished, or if it did, not uploaded here :)

**Comment by ErikSchierboom** [comment]
Sounds good :)

**Comment by sshine** [comment]
Either way is good with me; numbers or not. :-)

**Comment by nicolechalmers** [comment]
@ErikSchierboom It's taken me a while to get around to it (sorry!) but I have a designed a die with numbers on it. Would something like this work?

![dnd-character-dark](https://user-images.githubusercontent.com/5421823/55337272-3e62ca00-5496-11e9-87b3-d82f6a47d2e1.png)
![dnd-character-turquoise](https://user-images.githubusercontent.com/5421823/55337273-3e62ca00-5496-11e9-984f-6522bf1dfe31.png)
![dnd-character-white](https://user-images.githubusercontent.com/5421823/55337274-3e62ca00-5496-11e9-97ba-27b75460bb66.png)
![hex-bordered-green](https://user-images.githubusercontent.com/5421823/55337275-3e62ca00-5496-11e9-976f-7518880f6814.png)
![hex-bordered-turquoise](https://user-images.githubusercontent.com/5421823/55337276-3efb6080-5496-11e9-8e9b-da39c965fc87.png)
![hex-green](https://user-images.githubusercontent.com/5421823/55337278-3efb6080-5496-11e9-98a1-f8ccfe1484b9.png)
![hex-turquoise](https://user-images.githubusercontent.com/5421823/55337279-3f93f700-5496-11e9-8634-93ac9123062c.png)
![hex-white](https://user-images.githubusercontent.com/5421823/55337280-3f93f700-5496-11e9-896e-61973a3a005b.png)

**Comment by iHiD** [comment]
Done my end too. Thanks :)

**Comment by ErikSchierboom** [comment]
Love it!

**Comment by iHiD** [comment]
It's live now :)

**Comment by ErikSchierboom** [comment]
Check it out:

![image](https://user-images.githubusercontent.com/135246/55341473-fa2bf580-54a6-11e9-8a5c-fbffa92b4505.png)

Lovely icon @nicolechalmers!

**Comment by nicolechalmers** [comment]
Whoop!
