### ISSUE TITLE
Icon for Resistor Band

### ISSUE THREAD

**Issue by F3PiX** [exercism/website-icons#24]
@erikschierboom and I created a new Exercise, Resistor Code. 
Can we request a new icon?  

For inspiration: It's part of a series of Resistor Exercises, where each exercise will address more bands. In this first exercise it's about 1 'band', the rest of the series will be 2,3 and 4-6 bands. (And maybe after that: resistors in paralel and series.)
https://user-images.githubusercontent.com/6314687/52533780-3eb5d300-2d39-11e9-8f69-5a726735c294.png
![image](https://user-images.githubusercontent.com/6314687/52750884-c461a900-2fed-11e9-9123-d38aad13ac77.png)

https://github.com/exercism/problem-specifications/issues/1458

**Comment by bencoman** [comment]
Slightly off topic but a naive question about... 
> series of Resistor Exercises

By "series" of exercises do you mean separate folders...
   https://github.com/exercism/problem-specifications/.../exercises/HERE

why not just a one exercise with a series of tests ordered in increasing difficulty?

**Comment by SleeplessByte** [comment]
![image](https://user-images.githubusercontent.com/1964376/55024443-25be6400-4fff-11e9-8ddb-28f7f012ab64.png)

Note that this is also live in `javascript`.

**Comment by SleeplessByte** [comment]
@bencoman best to ask this in `problem-specifications`, or better yet slack!

**Comment by nicolechalmers** [comment]
@F3PiX @ErikSchierboom Hello :) Would something like this be ok?

![resistor-code-dark](https://user-images.githubusercontent.com/5421823/55341035-cdbfab80-549d-11e9-8cd4-d2e8fc46a48f.png)
![resistor-code-turquoise](https://user-images.githubusercontent.com/5421823/55341036-ce584200-549d-11e9-966b-50eb12abb06a.png)
![resistor-code-white](https://user-images.githubusercontent.com/5421823/55341037-ce584200-549d-11e9-8848-d8b0eb2e6574.png)

**Comment by ErikSchierboom** [comment]
Absolutely!

**Comment by F3PiX** [comment]
I love it!

**Comment by F3PiX** [comment]
This is done, so I'm closing this.
