### ISSUE TITLE
Icon for Resistor Colors

### ISSUE THREAD

**Issue by F3PiX** [exercism/website-icons#25]
Number 2 in the Resistor is merged! 
Can we have another Resistor icon please? (There's an issue for # 1: #24)

The difference is: number 1 is about 1 color
Number 2 is about 2 colors.
And, yeah, number 3 will be about 3 colors.  

#24 has an image of what those colors look like on a Resistor. 

Thanks! :-)

**Comment by nicolechalmers** [comment]
@F3PiX @ErikSchierboom Would something like this work or is it too simliar to #24 ? My thinking is we can an extra filled-in band for each new Resistor exercise.

![resistor-code-dark-colors](https://user-images.githubusercontent.com/5421823/55341470-97366080-549e-11e9-82dd-15e92f72bd01.png) 
![resistor-code-turquoise-colors](https://user-images.githubusercontent.com/5421823/55341474-9998ba80-549e-11e9-95f6-bbea0fedc812.png)
![resistor-code-colors-white](https://user-images.githubusercontent.com/5421823/55341477-9c93ab00-549e-11e9-8221-c871d8f1dea8.png)

**Comment by F3PiX** [comment]
I noticed that opportunity on the first one :-)  Lovely!!!!!!

**Comment by SleeplessByte** [comment]
:heart:

**Comment by nicolechalmers** [comment]
Great! This is also good to go @iHiD

**Comment by macta** [comment]
yeah - nice icon, we have this one live too and are in need of an icon

**Comment by iHiD** [comment]
Merged and deployed as `resistor-color-duo`. Once tracks update their slugs this will work for them.

**Comment by iHiD** [comment]
Thanks @nicolechalmers
