### ISSUE TITLE
Icon for Tcl language track

### ISSUE THREAD

**Issue by sshine** [exercism/website-icons#26]
As I've started to work on the [Tcl track](https://github.com/exercism/tcl), I hereby request a language track logo.

As concluded in exercism/request-new-language-track#49, this logo can be used as we need:

- https://tcl.tk/images/plume.png

**Comment by iHiD** [comment]
(cc @nicolechalmers)

**Comment by iHiD** [comment]
This should be live. Thanks all.

**Comment by sshine** [comment]
Hooray! Thanks, @nicolechalmers and @ihid. :)

Ping @glennj!
