### ISSUE TITLE
Icon for Micro-blog

### ISSUE THREAD

**Issue by ccouzens** [exercism/website-icons#29]
I'm creating a new Exercise, Micro-blog.
Can I request a new icon?

https://github.com/exercism/problem-specifications/pull/1509/files

The problem's story is about making a social network that only allows very short posts of 5 characters. A theme of the tests is both non-english characters and emoji.

> You have identified a gap in the social media market for very very short
posts. Now that Twitter allows 280 character posts, people wanting quick
social media updates aren't being served. You decide to create your own
social media network.
>
> To make your product noteworthy, you make it extreme and only allow posts
of 5 or less characters. Any posts of more than 5 characters should be
truncated to 5.
>
> To allow your users to express themselves fully, you allow Emoji and
other Unicode.
>
> The task is to truncate input strings to 5 characters. 

I'm not a designer, so take my suggestions with a pinch of salt, but my ideas for this would be:
* a tribute of Twitter's logo (if that's allowed)
* a stylized speech bubble with precisely 5 dots

Thank you 🙂

Chris

**Comment by iHiD** [comment]
Awesome. Cool exercise idea too. Thanks. 

cc @nicolechalmers

**Comment by ErikSchierboom** [comment]
Any update on this icon? https://github.com/exercism/problem-specifications/pull/1509 is waiting for the icon before being merged (no pressure ;))

**Comment by nicolechalmers** [comment]
@ccouzens @ErikSchierboom Hey, sorry it's taken me a while to get around to looking at this. 
I've had a go at making a few designs based on Chris' ideas - thanks for those. 

<img width="419" alt="Screen Shot 2019-07-03 at 18 37 51" src="https://user-images.githubusercontent.com/5421823/60613157-37639480-9dc2-11e9-8c5e-5fe2a1afc011.png">
<img width="433" alt="Screen Shot 2019-07-03 at 18 37 57" src="https://user-images.githubusercontent.com/5421823/60613159-37639480-9dc2-11e9-81a9-71190a9c4227.png">
<img width="437" alt="Screen Shot 2019-07-03 at 18 38 02" src="https://user-images.githubusercontent.com/5421823/60613160-37fc2b00-9dc2-11e9-8395-ef738d1367be.png">

Do you like any of these? If so I will upload the correct formats. Otherwise, I will think about some alternative ideas.

Cool idea for an exercise by the way. :)

**Comment by ccouzens** [comment]
Hi @nicolechalmers,

Thank you so much for these. They're all great!

I especially like the last one, because it looks the most fun to me and it still conveys the 5 characters.

Thanks,

Chris

**Comment by ErikSchierboom** [comment]
I like the second and last one best. I'm fine with both of them, the both look great! Great work @nicolechalmers!

**Comment by iHiD** [comment]
I really like the bottom one too, but it means "troubled" as is the equivalent of the "western" emoji 😣.

@nicolechalmers Would it be possible to change it to `(^_^)` which is the happy version?

**Comment by nicolechalmers** [comment]
@iHiD Great shout. I've changed it to a happier looking face. 
I've added the 3 colours I think are required below (one is white so you can't see it).

![micro-blog-dark](https://user-images.githubusercontent.com/5421823/60666758-b6f37100-9e5f-11e9-888c-2c181e943262.png)
![micro-blog-turquoise](https://user-images.githubusercontent.com/5421823/60666759-b78c0780-9e5f-11e9-9616-a5d9f5d86665.png)
![micro-blog-white](https://user-images.githubusercontent.com/5421823/60666760-b78c0780-9e5f-11e9-81ec-b72bf0a1cef5.png)

**Comment by sshine** [comment]
Since `micro-blog` focuses on Unicode, a variation could be one of the many Unicode table flipping emojis:

```
(ಠ_ಠ)
(ಠ‿ಠ)
...
```

https://gist.github.com/endolith/157796

**Comment by ccouzens** [comment]
Shall we move ahead with these https://github.com/exercism/website-icons/issues/29#issuecomment-508465972

And then if `(ಠ‿ಠ)` comes available switch to them?

**Comment by iHiD** [comment]
Yeah. I just need to find an hour to sort this and the other ones out. Sorry. It's on my radar.

**Comment by iHiD** [comment]
This is now live. Sorry for the delay, and thanks all.

**Comment by ccouzens** [comment]
Thank you @iHiD 

For reference, here's the commit d9687ea6945bd6714ac6d2240f756a3bc5fda143
