### ISSUE TITLE
Bash icon

### ISSUE THREAD

**Issue by budmc29** [exercism/website-icons#3]
To have Bash a proper track for V2 we require an icon for it.

Does the language have an official logo?  
  - Link: [https://tiswww.case.edu/php/chet/img/bash-logo-web.png](https://tiswww.case.edu/php/chet/img/bash-logo-web.png)  
   - Logo licence: [Free Art License](http://artlibre.org/licence/lal/en/)

Official website: [https://tiswww.case.edu/php/chet/bash/bashtop.html](https://tiswww.case.edu/php/chet/bash/bashtop.html)
Logo usage: [https://github.com/odb/official-bash-logo](https://github.com/odb/official-bash-logo)

**Comment by iHiD** [comment]
I think @nicolechalmers actually made one of these when she made the others. I'll check with her :)

**Comment by budmc29** [comment]
@iHiD any updates on this?

**Comment by budmc29** [comment]
A small reminder.

**Comment by iHiD** [comment]
Totally - we can do this for v2 launch :) We just need to get to v2 launch :S

**Comment by iHiD** [comment]
This has been done. Thanks :)
