### ISSUE TITLE
Icon for x86-64 Assembly track

### ISSUE THREAD

**Issue by bergjohan** [exercism/website-icons#30]
Hello,

I would like to request an icon for the [x86-64 Assembly](https://github.com/exercism/x86-64-assembly) track.

There is no official/unofficial logo so I suggest just spelling out the name for the icon. Assembly could be abbreviated to asm if it's too long.

**Comment by iHiD** [comment]
Thanks. Assigned to @nicolechalmers :)

**Comment by nicolechalmers** [comment]
@bergjohan Would something like this work for the icon?

![assembly-icon](https://user-images.githubusercontent.com/5421823/62779160-4d8fff00-baaa-11e9-8534-d3f17248b073.png)

In hex (as shown on Track main page):
![assembly-hex](https://user-images.githubusercontent.com/5421823/62779159-4cf76880-baaa-11e9-8318-e20a1aaa913a.png)

**Comment by bergjohan** [comment]
@nicolechalmers Thank you, it looks great :)

**Comment by iHiD** [comment]
Closing this. Thanks both.
