### ISSUE TITLE
Icon for Resistor Color Trio

### ISSUE THREAD

**Issue by F3PiX** [exercism/website-icons#31]
The next exercise in the series is in the making. 

This is number 3 in the series.
Number 1 is Resistor Color and is about one color band (icon: #24)
Number 2 is Resistor Color Duo and is about two bands (icon: #25)
Number 3, this one, is Resistor Color Trio, and yes! it has three bands 🙃 .

Can we have a logo please? 

(The same icon as in #25, but with an extra band.)

**Comment by nicolechalmers** [comment]
@F3PiX Here's number 3 in the series:

Turquoise
![resistor-code-colors-3-turquoise](https://user-images.githubusercontent.com/5421823/62783883-1e32bf80-bab5-11e9-8284-e2d737750da6.png)

White
![resistor-code-colors-3-white](https://user-images.githubusercontent.com/5421823/62783888-212db000-bab5-11e9-927a-c588834c74a9.png)

**Comment by imrehg** [comment]
Currently the icons for the Resistor Color Trio returns 403 errors
```
resistor-color-trio-turquoise.png:1 Failed to load resource: the server responded with a status of 403 ()
resistor-color-trio-white.png:1 Failed to load resource: the server responded with a status of 403 ()
resistor-color-trio-dark.png:1 Failed to load resource: the server responded with a status of 403 ()
```

![Screenshot_2019-08-20_12-11-37](https://user-images.githubusercontent.com/38863/63342686-06282f00-c344-11e9-85b0-cd5cabee369f.png)

(the second from the right in the boxes)

**Comment by iHiD** [comment]
Yeah. I've not done this yet.

**Comment by F3PiX** [comment]
And I forgot to cheer! Thanks, @nicolechalmers !!

**Comment by iHiD** [comment]
Done. Sorry for the delay and thanks y'all!
