### ISSUE TITLE
Icon for Knapsack exercise

### ISSUE THREAD

**Issue by glennj** [exercism/website-icons#32]
https://github.com/exercism/problem-specifications/tree/master/exercises/knapsack

This exercise is about maximizing the value of items that can fit into a knapsack, so an icon of a literal knapsack/backpack would be appropriate.

**Comment by nicolechalmers** [comment]
Thank you for providing details @glennj 

Would any of these icons work? If so, do you have a preference?

![knapsack-turquoise-1](https://user-images.githubusercontent.com/5421823/62778001-10763d80-baa7-11e9-8a7d-a65e276326bf.png)
![knapsack-turquoise-2](https://user-images.githubusercontent.com/5421823/62778002-110ed400-baa7-11e9-9419-bdcfc4cfc873.png)
![knapsack-turquoise-3](https://user-images.githubusercontent.com/5421823/62778376-27695f80-baa8-11e9-8dbc-9107167070ac.png)
![knapsack-turquoise-4](https://user-images.githubusercontent.com/5421823/62778377-27695f80-baa8-11e9-8f4e-621c3a0896a1.png)

**Comment by iHiD** [comment]
I like https://user-images.githubusercontent.com/5421823/62778002-110ed400-baa7-11e9-9419-bdcfc4cfc873.png

**Comment by iHiD** [comment]
Uploading this now.
