### ISSUE TITLE
Icon for Macros exercise

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/website-icons#33]
It appears the 'Macros' exercise is missing an icon.

![Screenshot from 2019-08-21 09-52-53](https://user-images.githubusercontent.com/1254212/63438157-dc314400-c3f9-11e9-8757-c20e845a27f4.png)

**Comment by iHiD** [comment]
@PatrickMcSweeny Which track is this? Do you have a link to where it's defined please?

**Comment by PatrickMcSweeny** [comment]
It's from the Rust track.

https://exercism.io/my/tracks/rust

**Comment by iHiD** [comment]
@PatrickMcSweeny Thanks.

@nicolechalmers Description here: https://github.com/exercism/problem-specifications/blob/master/exercises/matrix/description.md

**Comment by PatrickMcSweeny** [comment]
@iHiD It looks like you linked to the description for the 'matrix' exercise. Macros isn't listed in the problem-specifications repo, but here is the readme for the Rust exercise:

https://github.com/exercism/rust/tree/master/exercises/macros

**Comment by iHiD** [comment]
Ah. Thanks. Yes, this is why it doesn't have an icon - it's not an official exercise. Tracks need to tell us when they make unofficial ones and add them.

@nicolechalmers Let's chat about the icon because I have no idea what will work :)

**Comment by nicolechalmers** [comment]
@iHiD Are these ok?

White:
![macros](https://user-images.githubusercontent.com/5421823/65245684-f0458f80-dae4-11e9-8864-f80c0a34455b.png)

Turquoise:
![macros-t](https://user-images.githubusercontent.com/5421823/65245702-f89dca80-dae4-11e9-8694-c63d3ca2dfe2.png)

Grey/dark:
![marcos-d](https://user-images.githubusercontent.com/5421823/65245840-3e5a9300-dae5-11e9-9392-c9932547b11d.png)

**Comment by iHiD** [comment]
I'm uploading this now.
