### ISSUE TITLE
Icon for square-root

### ISSUE THREAD

**Issue by wolf99** [exercism/website-icons#34]
I'm creating a new exercise, square-root.
Can I request a new icon?

https://github.com/exercism/problem-specifications/pull/1582

The icon could be a simple radical symbol (the root sign) with the index of 2 (indicating square root rather than any other root) and a radicand (the number under the root sign) of x. Something similar to the symbol found on the related calculator key.

Thanks!

**Comment by iHiD** [comment]
@nicolechalmers Could you do this one pls? :)

**Comment by nicolechalmers** [comment]
@wolf99 Thank you for the thorough explanation. :)

Will this design work for the icon?

Grey/dark:
![square-root-d](https://user-images.githubusercontent.com/5421823/65247069-a4e0b080-dae7-11e9-9b45-5b39e9fad047.png)
Turquoise:
![square-root-t](https://user-images.githubusercontent.com/5421823/65247070-a4e0b080-dae7-11e9-91a2-b6cbd2f9b0b6.png)
White:
![square-root](https://user-images.githubusercontent.com/5421823/65247072-a4e0b080-dae7-11e9-8134-2b3f68c46638.png)

**Comment by iHiD** [comment]
Thanks both. I've put this live.

**Comment by wolf99** [comment]
Thanks both!
