### ISSUE TITLE
Icon for Microwave is missing in Ruby track

### ISSUE THREAD

**Issue by biancapower** [exercism/website-icons#38]
The Microwave icon is missing - the image linked to (https://assets.exercism.io/exercises/microwave-white.png) doesn't exist in this repo.

<img width="429" alt="Screen Shot 2020-07-01 at 8 04 24 am" src="https://user-images.githubusercontent.com/30207144/86181522-7e20d180-bb71-11ea-9b1b-37a820e95231.png">

<img width="584" alt="Screen Shot 2020-07-01 at 8 02 18 am" src="https://user-images.githubusercontent.com/30207144/86181349-30a46480-bb71-11ea-81cd-3f82a45d1a0c.png">

<img width="314" alt="Screen Shot 2020-07-01 at 8 06 15 am" src="https://user-images.githubusercontent.com/30207144/86181633-be804f80-bb71-11ea-8fed-fa07ccf7a490.png">

**Comment by iHiD** [comment]
Thanks for this!

When people add exercises, they're supposed to tag here to get us to create an exercise, but that step seems to have been missed for this exercise :) 

I'll get it sorted in the next few days.
