### ISSUE TITLE
ReasonML needs a logo

### ISSUE THREAD

**Issue by iHiD** [exercism/website-icons#5]
The ReasonML track is just about ready to launch.

https://github.com/exercism/request-new-language-track/issues/41

The official logo appears to be
https://reasonml.github.io/img/reason.svg

**Comment by nicolechalmers** [comment]
@iHiD Here's the logo in turquoise and white.

![reason-t](https://user-images.githubusercontent.com/5421823/43049519-791bd6fa-8df9-11e8-8aa9-b9baca1cef59.png)
![reason-w](https://user-images.githubusercontent.com/5421823/43049521-7ade7f38-8df9-11e8-9970-812ced889be9.png)

**Comment by ccare** [comment]
Hi, sorry, but I need them in the same format as the 'logos/' folder. They seem to be about 230 px wide and on transparent. E.g. for Bash

https://github.com/exercism/website-icons/blob/master/tracks/logos/bash-t.png
https://github.com/exercism/website-icons/blob/master/tracks/logos/bash.png

Those ones did some weird things. e.g
<img width="406" alt="screen shot 2018-07-23 at 09 59 18" src="https://user-images.githubusercontent.com/441154/43067380-202a46d8-8e5f-11e8-93c0-6fb4bd63e85e.png">

**Comment by ccare** [comment]
@nicolechalmers , sorry. I think I need turquoise on transparent, and white on transparent. No backgrounds.

**Comment by nicolechalmers** [comment]
@ccare The square around the "RE" is part of the design like https://github.com/exercism/website-icons/blob/master/tracks/logos/javascript-t.png. Is that want you mean?

**Comment by iHiD** [comment]
@ccare I think the ones above are correct.

**Comment by iHiD** [comment]
Deployed.
