### ISSUE TITLE
When submitting a new exercise should a glyph for the exercise also be included?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/website-icons#7]
@rpottsoh commented on [Thu Jul 19 2018](https://github.com/exercism/problem-specifications/issues/1268)

@kytrinyx or @iHid,

I think this issue has not been raised.  I know, right now, the development team is taking care of glyphs for the exercises.  Is there a mechanism in place (or planned) to help take care of implementing icons for new exercises as they are added to this repo?

---

@rpottsoh commented on [Thu Jul 19 2018](https://github.com/exercism/problem-specifications/issues/1268#issuecomment-406378806)

I realize that the glyphs do not exist in this repo, at the moment.

---

@iHiD commented on [Fri Jul 20 2018](https://github.com/exercism/problem-specifications/issues/1268#issuecomment-406536093)

The best method would be to create an issue on exercism/website-icons and tag @nicolechalmers and me in it.

**Comment by rpottsoh** [comment]
@iHiD and @nicolechalmers    For your consideration.

**Comment by iHiD** [comment]
Sorry, @rpottsoh I wasn't clear.

What I meant was when a new exercises is added to specifications, a new issue should be opened here to inform the design team that a new icon needs designing. Any suggestions or examples in that issue will be appreciated too :)

**Comment by rpottsoh** [comment]
Lol.  That makes sense too.  No harm no foul.
