### ISSUE TITLE
The Nim icon is a bit big

### ISSUE THREAD

**Issue by iHiD** [exercism/website-icons#8]
It seems to have outgrown its surroundings :)

https://exercism.io/my/tracks/nim

**Comment by nicolechalmers** [comment]
@iHiD This should be better.

Turquoise:
![nim-t](https://user-images.githubusercontent.com/5421823/43046097-ecbc0fd8-8dc4-11e8-90d8-16ebadf2cdd9.png)

White:
![nim-w](https://user-images.githubusercontent.com/5421823/43046098-ecea7d3c-8dc4-11e8-959a-b94adf262795.png)

**Comment by iHiD** [comment]
Thanks. @ccare can you action this when you're next on pls?

**Comment by nicolechalmers** [comment]
Let's try these. They're 214 pixels wide which is the same as ReasonML.

turquoise:
![nim-t](https://user-images.githubusercontent.com/5421823/44029126-1b237ce0-9ef4-11e8-892d-18ef2caa46a3.png)
white:
![nim](https://user-images.githubusercontent.com/5421823/44029128-1b8743e2-9ef4-11e8-8ca7-98b532eba3a8.png)

**Comment by iHiD** [comment]
Deployed.
