### ISSUE TITLE
Pharo needs a logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/website-icons#9]
The official language site is here:
https://pharo.org/

The track maintainers made a bit of a suggestion here: https://github.com/exercism/pharo/blob/ccf02659a88c8c32e0040fab4a82e1ea478adcce/img/icon.png

**Comment by macta** [comment]
Any view on how long it takes to get this moved forward?

**Comment by iHiD** [comment]
It'll get done before Pharo is ready to go live. Do we have a timescale on that?

**Comment by bencoman** [comment]
btw, if a vector format is needed, some available [here](http://files.pharo.org/media/logo/). I don't remember which one I worked off to derive the one proposed above.

**Comment by iHiD** [comment]
Cc @nicolechalmers

**Comment by nicolechalmers** [comment]
@iHiD Here you go. 

Dark:
![pharo-dark](https://user-images.githubusercontent.com/5421823/55329078-af4db600-5485-11e9-915e-43e0b54b390d.png)
Turquoise/green:
![pharo-t](https://user-images.githubusercontent.com/5421823/55329079-af4db600-5485-11e9-9047-5f68a5a19c0c.png)
White:
![pharo-white](https://user-images.githubusercontent.com/5421823/55329080-afe64c80-5485-11e9-9134-45f91d6913b6.png)

**Comment by iHiD** [comment]
This is done. Thanks all.
