### ISSUE TITLE
Add Icon for Elixir `new-passport` concept exercise

### ISSUE THREAD

**Issue by jiegillet** [exercism/website-icons#94]
@iHiD @taiyab 
Elixir has a new [concept exercise here](https://exercism.org/tracks/elixir/exercises/new-passport) which needs an icon.
The story is about getting a new passport from the city office, so my suggestion would be a... passport. Yes, indeed.

There has been talk of forking that exercise, so possibly it will be used by other tracks.

**Comment by taiyab** [comment]
@iHiD https://github.com/exercism/website-icons/pull/100

**Comment by iHiD** [comment]
Thanks!
